---
title: "index"
format: html
editor: visual
---

## RUM For Trails

Here need to make the data into wide format to create the utility functions.

```{r}
#after running Valdos code


mlogit_clean=mlogit_clean[c(1:11,40:47,85:87)]
mlogit_clean$Alternative[which(mlogit_clean$Alternative==1)]="alt1"
mlogit_clean$Alternative[which(mlogit_clean$Alternative=="2")]="alt2"
mlogit_clean$Alternative[which(mlogit_clean$Alternative=="3")]="alt3"
#mlogit_clean$Choice.Binary=NULL
#Note design_ngene still says 50
# mlogit_clean$Cost[which(mlogit_clean$Cost==50)]=40
mlogit_clean_wide=reshape(mlogit_clean,timevar = "Alternative",
idvar = c(1:3,5,7),
direction = "wide" ) # Each respondent-choice task becomes one row, with separate columns for each alternative’s attributes.

apollo_control <- list(
  modelName  = "Trail_Choice",
  modelDescr = "Simple MNL model with trail alternatives",
  indivID    = "RID" ,
  panelData = TRUE
)
database=mlogit_clean_wide

```

To expand we will create for each alternative there is a low, medium, high for each alternative 1 and 2 . Alternative 3 is all zeros so we can deal with that in the utility function.

```{r}
database$Habitat_QualityL.alt1=0
database$Habitat_QualityL.alt1[which(database$Habitat_Quality.alt1=="Low")]=1
database$Habitat_QualityM.alt1=0
database$Habitat_QualityM.alt1[which(database$Habitat_Quality.alt1=="Medium")]=1
database$Habitat_QualityH.alt1=0
database$Habitat_QualityH.alt1[which(database$Habitat_Quality.alt1=="High")]=1

database$Habitat_QualityL.alt2=0
database$Habitat_QualityL.alt2[which(database$Habitat_Quality.alt2=="Low")]=1
database$Habitat_QualityM.alt2=0
database$Habitat_QualityM.alt2[which(database$Habitat_Quality.alt2=="Medium")]=1
database$Habitat_QualityH.alt2=0
database$Habitat_QualityH.alt2[which(database$Habitat_Quality.alt2=="High")]=1


database$Trail_ConditionL.alt1=0
database$Trail_ConditionL.alt1[which(database$Trail_Condition.alt1=="Low")]=1
database$Trail_ConditionM.alt1=0
database$Trail_ConditionM.alt1[which(database$Trail_Condition.alt1=="Medium")]=1
database$Trail_ConditionH.alt1=0
database$Trail_ConditionH.alt1[which(database$Trail_Condition.alt1=="High")]=1

database$Trail_ConditionL.alt2=0
database$Trail_ConditionL.alt2[which(database$Trail_Condition.alt2=="Low")]=1
database$Trail_ConditionM.alt2=0
database$Trail_ConditionM.alt2[which(database$Trail_Condition.alt2=="Medium")]=1
database$Trail_ConditionH.alt2=0
database$Trail_ConditionH.alt2[which(database$Trail_Condition.alt2=="High")]=1



## Crowding logic is reverse here

database$CrowdingL.alt1=0
database$CrowdingL.alt1[which(database$Crowding.alt1=="High")]=1
database$CrowdingM.alt1=0
database$CrowdingM.alt1[which(database$Crowding.alt1=="Medium")]=1
database$CrowdingH.alt1=0
database$CrowdingH.alt1[which(database$Crowding.alt1=="Low")]=1



database$CrowdingL.alt2=0
database$CrowdingL.alt2[which(database$Crowding.alt2=="High")]=1
database$CrowdingM.alt2=0
database$CrowdingM.alt2[which(database$Crowding.alt2=="Medium")]=1
database$CrowdingH.alt2=0
database$CrowdingH.alt2[which(database$Crowding.alt2=="Low")]=1



```

Need to create some demographic info to control in the regression.

```{r}
database$Choice.Task.alt1
database$Resident=0
database$Resident[which(database$Zipverified.alt1=="Resident")]=1

database$Demo_Age_num=as.integer(factor(
    database$Demo_Age.alt1,
    levels = c(
        "Under 18",
        "18-24 years old",
        "25-34 years old",
        "35-44 years old",
        "45-54 years old",
        "55-64 years old",
        "65+ years old"
    ),
    labels = 1:7
))

database$Sex_binary <- ifelse(database$Demo_Sex.alt1 == "Female", 1,
                              ifelse(database$Demo_Sex.alt1 == "Male", 0, 0))

#database=database[c(1,3,4,6,10,11:18,28,46, 55:81)]
colnames(database)[1]="RID"
colnames(database)[3]="choice"
database$choice=as.numeric(database$choice)
```

# Apollo code

```{r}

apollo_beta <- c(
  b_Habitat_QualityMed  = 0,
  b_Habitat_QualityHigh = 0,
  b_Trail_ConditionMed  = 0,
  b_Trail_ConditionHigh = 0,
  b_CrowdingMed         = 0,
  b_CrowdingHigh        = 0,
  b_cost                = 0,
  b_resident            = 0,
  b_age                 = 0,
  b_HHIncome_num        = 0,
  b_view =0,
  b_sex = 0
)
apollo_fixed <- c()


apollo_inputs<-apollo_validateInputs()
```

```{r}
apollo_probabilities=function(apollo_beta, apollo_inputs, functionality="estimate"){
  
  ### Attach inputs and detach after function exit
  apollo_attach(apollo_beta, apollo_inputs)
  on.exit(apollo_detach(apollo_beta, apollo_inputs))
  
  ### Create list of probabilities P
  P = list()
  
  ### List of utilities: these must use the same names as in mnl_settings, order is irrelevant
  V = list()
  V[["alt1"]]  = b_Habitat_QualityMed*Habitat_QualityM.alt1  + b_Habitat_QualityHigh * Habitat_QualityH.alt1+b_Trail_ConditionMed*Trail_ConditionM.alt1+b_Trail_ConditionHigh*Trail_ConditionH.alt1+b_CrowdingMed*CrowdingM.alt1+ b_CrowdingHigh*CrowdingH.alt1+b_cost*Cost.alt1+b_resident*Resident+b_age*Demo_Age_num+b_sex*Sex_binary+b_HHIncome_num*HHIncome_num+b_view*viewpoint
  
  V[["alt2"]]  = b_Habitat_QualityMed*Habitat_QualityM.alt2  + b_Habitat_QualityHigh * Habitat_QualityH.alt2+b_Trail_ConditionMed*Trail_ConditionM.alt2+b_Trail_ConditionHigh*Trail_ConditionH.alt2+b_CrowdingMed*CrowdingM.alt2+ b_CrowdingHigh*CrowdingH.alt2+b_cost*Cost.alt2+b_resident*Resident+b_age*Demo_Age_num+b_sex*Sex_binary+b_HHIncome_num*HHIncome_num+b_view*viewpoint
  
  V[['alt3']] = 0
  
  ### Define settings for MNL model component
  mnl_settings = list(
    alternatives  = c(alt1=1, alt2=2, alt3=3), 
    avail         = list(alt1=1, alt2=1, alt3=1), 
    choiceVar     = choice,
    utilities     = V
  )
  
  ### Compute probabilities using MNL model
  P[["model"]] = apollo_mnl(mnl_settings, functionality)
  
  ### Take product across observation for same individual
  P = apollo_panelProd(P, apollo_inputs, functionality)
  
  ### Prepare and return outputs of function
  P = apollo_prepareProb(P, apollo_inputs, functionality)
  return(P)
}
```

```{r}
model = apollo_estimate(apollo_beta, apollo_fixed, apollo_probabilities, apollo_inputs)

```
